---
sudo: false

language: node_js
node_js:
  - node # latest stable

env:
  - ELM_VERSION=0.18.0 ELM_TEST_VERSION=0.18.7 ELM_VERIFY_EXAMPLES_VERSION=1.0.2

cache:
  directories:
    - sysconfcpus

install:
  # Travis exposes a few more CPUs (like... 14 more) than the code can actually
  # use. This program allows us to lie to the compiler about how many CPUs it
  # can use. In this case, we're actually telling the truth about the number of
  # usable CPUs, so build times go way down.
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

  - npm install -g elm@${ELM_VERSION} elm-test@${ELM_TEST_VERSION} elm-verify-examples@ELM_VERIFY_EXAMPLES_VERSION
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make elm-stuff
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make tests/elm-stuff

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make documentation.json
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make test
