sudo: false

cache:
  directories:
    - tests/elm-stuff

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.17.1 TARGET_NODE_VERSION=node ELM_TEST_VERSION=0.18.6

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST_VERSION
  - git clone https://github.com/NoRedInk/elm-ops-tooling
  - elm-ops-tooling/with_retry.rb elm package install --yes
  
script:
  - elm-test
